Stop search engines from crawling the tool
alphagov/govuk-content-explorer pull request #11
Opened 2017-09-12 09:53 UTC by brenetic

We do not want any results from this tool appearing in search engines results.

https://trello.com/c/6qUAhPQi/304-stop-internal-apps-and-deprecated-stuff-appearing-in-search-engines

2017-09-12 10:01 UTC, suzannehamilton commented
I'm not very familiar with Flask, but does adding robots.txt to the project root mean that it will be served on the site root? The other files in the project root aren't part of the site itself.

2017-09-12 13:03 UTC, brenetic commented
@suzannehamilton thanks! updated

2017-09-13 13:51 UTC, MatMoore commented on explorer/api.py
> +@app.route("/robots.txt")
this is a decorator for the `main` function, so I'd expect it to still serve the compare page/main page at `robots.txt`.

Should this use something like this? http://flask.pocoo.org/docs/0.12/api/#flask.send_from_directory

I'm assuming there's not a simple way to make heroku serve this?

2017-09-13 13:52 UTC, MatMoore requested changes
see inline comment

2017-09-13 14:51 UTC, MatMoore approved these changes

2017-09-13 15:05 UTC, suzannehamilton commented on explorer/api.py
> +    return send_static_file("robots.txt")
Does robots.txt have to be in the static directory for this to work?

2017-09-13 16:43 UTC, MatMoore approved these changes

2017-09-13 16:44 UTC, merged